language: generic 
sudo: required 
services:
  - docker

before_install:
  - docker build -t integrald-503/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true integrald-503/docker-react npm run test